[package]
name = "litime"
version = "0.4.0"
authors = ["Axel Örn Sigurðsson <axel@absalon.is>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "readme.md"
edition = "2018"

[dependencies]
textwrap = "0.10"
rand = "0.5.5"
chrono = "0.4"
clap = "2.32.0"
regex = "1.0.4"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"

[profile.release]
lto = true
