[package]
name = "litime"
version = "1.0.0"
authors = ["Axel <litime@absalon.dev>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "README.md"
edition = "2021"

[dependencies]
textwrap = "0.16.0"
rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
termsize = "0.1.6"
time = { version = "0.3.17", features = ["local-offset", "parsing"] }
anyhow = "1.0.66"

[profile.release]
lto = true
strip = true

[dev-dependencies]
pretty_assertions = "1.3.0"
