[package]
name = "litime"
version = "0.6.0"
authors = ["Axel <dev@absalon.is>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "readme.md"
edition = "2018"

[dependencies]
textwrap = "0.14.2"
rand = "0.8.4"
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["derive"] }
regex = "1.5.4"
serde = "1.0.132"
serde_json = "1.0.73"
serde_derive = "1.0.132"

[profile.release]
lto = true

[dev-dependencies]
pretty_assertions = "1.0.0"
