[package]
name = "litime"
version = "0.7.2"
authors = ["Axel <dev@absalon.is>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "readme.md"
edition = "2018"

[dependencies]
textwrap = "0.14.2"
rand = "0.8.4"
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["derive"] }
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
termsize = "0.1.6"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dev-dependencies]
pretty_assertions = "1.0.0"
