[package]
name = "litime"
version = "0.2.0"
authors = ["Axel Örn Sigurðsson <axel@absalon.is>"]

[dependencies]
colored = "1.6"
textwrap = "0.10"
rand = "0.5.5"
chrono = "0.4"
clap = "2.32.0"
regex = "1.0.4"
