[package]
name = "litime"
version = "0.4.0"
authors = ["Axel Örn Sigurðsson <axel@absalon.is>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "readme.md"
edition = "2018"

[dependencies]
textwrap = "0.14.0"
rand = "0.8.4"
chrono = "0.4.19"
clap = "2.33.3"
regex = "1.5.4"
serde = "1.0.126"
serde_json = "1.0.64"
serde_derive = "1.0.126"

[profile.release]
lto = true
