[package]
name = "litime"
version = "0.8.1"
authors = ["Axel <dev@absalon.is>"]
description = "A command line tool to display the current time ish with a literature quote"
repository = "https://github.com/ikornaselur/litime"
license = "CC-BY-NC-SA-2.5"
readme = "README.md"
edition = "2021"

[dependencies]
textwrap = "0.15.0"
rand = "0.8.4"
clap = { version = "3.2.21", features = ["derive"] }
termsize = "0.1.6"
time = { version = "0.3.9", features = ["local-offset", "parsing"] }
anyhow = "1.0.65"

[profile.release]
lto = true
strip = true

[dev-dependencies]
pretty_assertions = "1.0.0"
