on:
  release:
    types: [published]

name: Build artefacts

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - name: linux-armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            command: cross
          - name: linux-amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cargo
          - name: win-amd64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            command: cargo
          - name: macos-amd64
            os: macos-latest
            target: x86_64-apple-darwin
            command: cargo
          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            command: cargo
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
 
      - name: Build Binary
        run: ${{ matrix.command }} build --verbose --locked --release --target ${{ matrix.target }}

      - name: Rename binary for release (windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: Rename-Item target\${{ matrix.target }}\release\litime.exe litime-${{ matrix.target }}.exe

      - name: Rename binary for release (other)
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: mv target/${{ matrix.target }}/release/litime target/${{ matrix.target }}/release/litime-${{ matrix.target }}

      - name: Attach artefact to release (windows)
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          files: target/${{ matrix.target }}/release/litime-${{ matrix.target }}.exe

      - name: Attach artefact to release (other)
        uses: softprops/action-gh-release@v1
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          files: target/${{ matrix.target }}/release/litime-${{ matrix.target }}
