on:
  release:
    types: [published]

name: Build artefacts

jobs:
  armv7-unknown-linux-gnueabihf:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build --target armv7-unknown-linux-gnueabihf --release

      - run: mv target/armv7-unknown-linux-gnueabihf/release/litime target/armv7-unknown-linux-gnueabihf/release/litime-armv7-unknown-linux-gnueabihf

      - uses: softprops/action-gh-release@v1
        with:
          files: target/armv7-unknown-linux-gnueabihf/release/litime-armv7-unknown-linux-gnueabihf

  x86_64-unknown-linux-gnu:

    name: Linux 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build --target x86_64-unknown-linux-gnu --release

      - run: mv target/x86_64-unknown-linux-gnu/release/litime target/x86_64-unknown-linux-gnu/release/litime-x86_64-unknown-linux-gnu

      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/litime-x86_64-unknown-linux-gnu

  x86_64-apple-darwin:
    name: macOS 64-bit x86
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build --target x86_64-apple-darwin --release

      - run: mv target/x86_64-apple-darwin/release/litime target/x86_64-apple-darwin/release/litime-x86_64-apple-darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-apple-darwin/release/litime-x86_64-apple-darwin

  aarch64-apple-darwin:
    name: macOS 64-bit aarch64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build--target aarch64-apple-darwin --release

      - run: mv target/aarch64-apple-darwin/release/litime target/aarch64-apple-darwin/release/litime-aarch64-apple-darwin

      - uses: softprops/action-gh-release@v1
        with:
          files: target/aarch64-apple-darwin/release/litime-aarch64-apple-darwin

  x86_64-pc-windows-msvc:
    name: Windows 64-bit
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build --target x86_64-pc-windows-msvc --release

      - run: Rename-Item target\x86_64-pc-windows-msvc\release\litime.exe litime-x86_64-pc-windows-msvc.exe

      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-pc-windows-msvc/release/litime-x86_64-pc-windows-msvc.exe
